drop table if exists post;
drop table if exists member;

create table post (
    id bigint generated by default as identity,
    content varchar(255),
    author varchar(255),
    title varchar(255),
    primary key (id)
);
create table member (
    id bigint generated by default as identity,
    member_id varchar(255),
    password varchar(255),
    primary key (id)
);